<?php
return [
    'default_date_format'=>     'D MMM YYYY',
    'default_datetime_format'=> 'D MMM YYYY, HH:mm',
    'html_direction' =>         'rtl',
    'styles' =>                 [],
    'js'=>                      [],
    'route_prefix' =>           'Drivers',
    'web_middleware' =>         'web',
    'view_namespace' =>         'Drivers::',
    'package_path'=>            base_path().'\\vendor\Amerhendy\Drivers\src\\',
    'nameSpace'=>               'Amerhendy\Drivers',
    'Controllers'=>             'Amerhendy\Drivers\App\Http\Controllers',
    'language'=>                'arabic',
    'lang'=>                    'ar-eg',
    'dir'=>                     'rtl',
    'ENCODE'=>                  'UTF-8',
    'root_disk_name'=>          'Drivers',
    'tables'=>[
        'cars'=>                'office_cars',
        'chairmen'=>            'office_chairmen',
        'employers'=>           'office_employers',
        'drivers'=>             'office_drivers',
        'chairmenmamorias'=>    'offics_chairmenmamorias',
        'employersmamorias'=>   'offics_employersmamorias',
        'driversmamorias'=>     'offics_driversmamorias',
    ],
    'columns'=>[
        'info'=>                'info',
        'persons_name'=>        'name',
        'userid'=>              'userid',
        'chairmanid'=>          'chairman_id',
        'places'=>              'places',
        'startend'=>            'startend',
        'amount'=>              'amount',
        'eqameamount'=>         'eqameamount',
        'print'=>               'print',
        'exit'=>                'exit',
        'taswia'=>              'taswia',
        'eqama'=>               'eqama',
        'enumTF'=>              ['true','false'],
        'driver'=>              'driver',
        'report'=>              'report',
        'reson'=>               'reson',
        'car'=>                 'car',
        'addad'=>               'addad',

    ],
];
